Merge feature/parser-implementation
AM311/Quoridor pull request #53
Opened 2024-11-11 14:11 UTC by DanieleMaijnelli

Implemented Parser and added corresponding tests, verify correctness and management of special cases.

2024-11-11 20:54 UTC, AM311 commented
There seems to be a problem when parsing more than one string with the same parser, since fields are not set to null.
This may cause inconsintency problems and need to be fixed.

2024-11-11 21:15 UTC, AM311 requested changes

2024-11-11 21:15 UTC, AM311 commented on src/main/java/it/units/sdm/quoridor/cli/parser/StandardQuoridorParser.java
There seems to be a problem when parsing more than one string with the same parser, since fields are not set to null.
This may cause inconsintency problems and need to be fixed.

2024-11-11 21:15 UTC, AM311 commented on src/main/java/it/units/sdm/quoridor/cli/parser/StandardQuoridorParser.java
Improve command type identification from the number of parameters: if the number of arguments is not coherent, an exception can be immediately thrown instead of trying to parse the string anyway.

2024-11-11 21:15 UTC, AM311 commented on src/test/java/StandardQuoridorParserTest.java
Add tests for assessing correctness of operations when parsing more than one string with the same parser.

2024-11-13 15:27 UTC, AM311 commented
@matfumis take a look at this new feature and please confirm that all is good for you!

2024-11-13 15:36 UTC, AM311 approved these changes

2024-11-13 17:41 UTC, matfumis approved these changes

2024-11-14 09:46 UTC, AM311 commented
Ready to merge.

Please, commit and push the jacoco coverage file before merging.

2024-11-18 16:18 UTC, merged